version: '3.8'

services:
  draw_blue:
    image: python:3.9-slim
    restart: unless-stopped
    container_name: draw_blue
    working_dir: /app
    volumes:
      - ./draw:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             python app.py"
    ports:
      - "5179:5179"
    networks:
      - draw_network

networks:
  draw_network:
    external: true
